Make Receiver inheritance public instead of implicitly private
Otherwise you get an error when trying to run the example.

/home/lemling/Dokumente/Proggen/BaconGameJam/bgj09/entityx/entityx/Event.h: In instantiation of ‘void entityx::EventManager::subscribe(Receiver&) [with E = PlayerInstrucionEvent; Receiver = MovementSystem]’:
/home/lemling/Dokumente/Proggen/BaconGameJam/bgj09/src/system_movement.hpp:17:58:   required from here
/home/lemling/Dokumente/Proggen/BaconGameJam/bgj09/entityx/entityx/Event.h:130:26: error: ‘entityx::BaseReceiver’ is an inaccessible base of ‘MovementSystem’
     BaseReceiver &base = receiver;